#!/usr/bin/env python

import datetime, pytz
from ics import Calendar, Event


c = Calendar()
delta = {"hours":2}
tz = pytz.timezone("Europe/Vienna")
ltitle, ldate, e, lcal = [], [], [], []


with open(".config/igni-ical/plaintext", "r") as f:
    f = f.readlines()
    for i in range(len(f)):
        if i % 2:
            date_obj = datetime.datetime.strptime(f[i].strip(), "%d.%m.%Y %H:%M").astimezone(tz)
            ldate.append(date_obj)
        else:
           ltitle.append(f[i].strip())


with open(".config/igni-ical/igni.ics", "r", newline='') as f:
    f = f.readlines()
    lbuffer = []
    for i in range(len(f)):
        if not ("END:VCALENDAR" in f[i] or "BEGIN:VCALENDAR" in f[i] or\
                "VERSION:2.0" in f[i] or "PRODID:ics.py - http://git.io/lLljaA"\
                in f[i]):
            if "END:VEVENT" in f[i]:
                lbuffer.append(f[i])
                lcal.append(tuple(lbuffer))
                lbuffer.clear()
            else:
                lbuffer.append(f[i])
                    

for i in range(len(ltitle)):
    resultj, resultk = list(), list()
    for j, word in enumerate(lcal):
        for k, tupword in enumerate(lcal[j]):
            print(i)
            if tupword.find(ltitle[i]) > -1:
                resultj.append(j)
                resultk.append(k)
    if resultj:
        for g in range(len(resultj)):
            bufdate = lcal[resultj[g]][int(resultk[g])-1].strip().split(":")
            compdate = datetime.datetime.fromisoformat(bufdate[1]).astimezone(tz)
            if ldate[i] == compdate:
                ltitle.pop(i)
                ldate.pop(i)
                break

print(lcal)

with open(".config/igni-ical/igni.ics", "w", newline='') as f:
    for i in range(len(ltitle)):
        e.append(Event())
        e[i].name = ltitle[i]
        if ldate[i].strftime("%H%M") == "0000":
            ldate[i] = ldate[i].replace(day=ldate[i].day+1)
            e[i].begin = ldate[i].isoformat()
            e[i].make_all_day()
        else:
            e[i].begin = ldate[i].isoformat()
            e[i].duration = delta
        c.events.add(e[i])
    f.writelines(c.serialize_iter())
"""
    die lcal so herrichten, dass sie auch als events + uid eingespielt werden
    können
"""

# funktioniert dann überlegen ob ich das irgendwie automatisch machen kann mit
# hochladen in einen kalender... oder das skript irgendwo laufen lassen kann.
