#!/bin/bash

# the directory backup has to exist for this to work

fdate=$(date +%y%m%d)
buname=backup.${fdate}.tar.gz
snarname=differential${fdate}.snar

if [ -e "/home/$USER/backup/backup.tar.gz" ] && [ -e "/home/$USER/backup/differential.snar" ]
then
    cp /home/$USER/backup/differential.snar /home/$USER/backup/${snarname}
    sudo tar -cvvpzf /home/$USER/backup/${buname} -g /home/$USER/backup/${snarname} --exclude=.* --exclude=/home/$USER/backup/ /home/
else
    sudo tar -cvvpzf /home/$USER/backup/backup.tar.gz -g /home/$USER/backup/differential.snar --exclude=.* --exclude=/home/$USER/backup/ /home/
fi
