vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set relativenumber")
vim.cmd("set ignorecase")
vim.cmd("set ttyfast")
vim.cmd("set scrolloff=5")
